### ISSUE TITLE
Compilation fails with "concurrent insert not supported" on FreeBSD 12

### ISSUE THREAD

**Issue by Papabyte** [Level/rocksdb#131]
Hi

I try to run a project that uses RocksDB on FreeBSD 12.

I got this error when running npm install:
```
$ npm install rocksdb@3.1.0

> rocksdb@3.1.0 install /usr/home/obyte/headless-obyte/node_modules/rocksdb
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.16.0 runtime=node arch=x64 libc= platform=freebsd)
gmake: Entering directory '/usr/home/obyte/headless-obyte/node_modules/rocksdb/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-rocksdb/db/auto_roll_logger.o
In file included from ../deps/leveldb/leveldb-rocksdb/db/auto_roll_logger.cc:6:
In file included from ../deps/leveldb/leveldb-rocksdb/db/auto_roll_logger.h:13:
In file included from ../deps/leveldb/leveldb-rocksdb/db/filename.h:19:
In file included from ../deps/leveldb/leveldb-rocksdb/include/rocksdb/options.h:20:
In file included from ../deps/leveldb/leveldb-rocksdb/include/rocksdb/advanced_options.h:13:
../deps/leveldb/leveldb-rocksdb/include/rocksdb/memtablerep.h:101:5: error: cannot use 'throw' with exceptions disabled
    throw std::runtime_error("concurrent insert not supported");
    ^
1 error generated.
gmake: *** [deps/leveldb/leveldb.target.mk:299: Release/obj.target/leveldb/deps/leveldb/leveldb-rocksdb/db/auto_roll_logger.o] Error 1
gmake: Leaving directory '/usr/home/obyte/headless-obyte/node_modules/rocksdb/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System FreeBSD 12.0-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/obyte/headless-obyte/node_modules/rocksdb
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
```
I tried with node8-8.16.0, node10-10.16.0, rocksdb@3.1.0 and rocksdb@4.0.0. That always fails with same error.
Any idea how to fix?

**Comment by vweevers** [comment]
The relevant bit is `error: cannot use 'throw' with exceptions disabled`.

To enable that, maybe we need to add an `-fexceptions` flag to `binding.gyp`.

**Comment by NickNaso** [comment]
Hi everyone,
I think that @vweevers is right you need to enable the exception mechanism using the following flags:
```gyp
 'cflags!': [  '-fno-exceptions' ],
 'cflags_cc!': [ '-fno-exceptions' ]
```
You need to set the flags in the gyp file used to build the `rocksdb` dependency:
**[leveldb.gyp](https://github.com/Level/rocksdb/blob/master/deps/leveldb/leveldb.gyp)**

**Comment by vweevers** [comment]
Thanks @NickNaso. I think we should also add `OS_FREEBSD=1` define, similar to what [`leveldown` does](https://github.com/Level/leveldown/blob/084f10c24ed2d6438b79fa85b0015c007503a3ce/deps/leveldb/leveldb.gyp#L88-L101).

And while we're at it, update https://github.com/Level/rocksdb#supported-platforms. I think this was copied as-is from `leveldown` but `rocksdb` doesn't support the same platforms.

A PR is welcome!

**Comment by vweevers** [comment]
Would be cool to run our tests on FreeBSB.

Anyone have any experience with Cirrus CI? They have [FreeBSD VM's](https://cirrus-ci.org/guide/FreeBSD/)! And it's free for OSS.

**Comment by vweevers** [comment]
Trying out Cirrus CI on leveldown: https://github.com/Level/leveldown/pull/678
