### ISSUE TITLE
Electron tests fail on M1 (Apple Sillicon)

### ISSUE THREAD

**Issue by Nazgolze** [Level/rocksdb#172]
This issue only comes into play once you get past https://github.com/Level/rocksdb/issues/169

This is due to there not being a Mac ARM version for this version of electron. I wonder if it's enough to go to a newer version 
```
npm install> electron@6.1.12 postinstall /Users/juan/Desktop/testing/rocksdb/node_modules/electron
> node install.jsDownloading tmp-71299-0-electron-v6.1.12-darwin-arm64.zip
Error: GET https://github.com/electron/electron/releases/download/v6.1.12/electron-v6.1.12-darwin-arm64.zip returned 404
/Users/juan/Desktop/testing/rocksdb/node_modules/electron/install.js:53
  throw err
  ^Error: Failed to find Electron v6.1.12 for darwin-arm64 at https://github.com/electron/electron/releases/download/v6.1.12/electron-v6.1.12-darwin-arm64.zip
    at Request.<anonymous> (/Users/juan/Desktop/testing/rocksdb/node_modules/nugget/index.js:169:61)
    at Request.emit (events.js:314:20)
    at Request.onRequestResponse (/Users/juan/Desktop/testing/rocksdb/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:474:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@6.1.12 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@6.1.12 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juan/.npm/_logs/2021-06-09T07_38_46_905Z-debug.log
```

**Comment by Nazgolze** [comment]
my bad, i was looking at an old branch. I'll test on master and see if this is actually an issue

**Comment by Nazgolze** [comment]
Updated description

**Comment by vweevers** [comment]
This will probably take more time to figure out, so I suggest to temporarily disable Electron tests on mac. In your PR, could you remove `TEST_ELECTRON=1, ` from this line? 

https://github.com/Level/rocksdb/blob/5c8e0b9a4519ba8e9a25dc3b704f1bae395af214/.travis.yml#L29

With a comment like `# Electron tests are disabled (https://github.com/Level/rocksdb/issues/172)`
