### ISSUE TITLE
fatal error: linux/fs.h: No such file or directory

### ISSUE THREAD

**Issue by plainweaver** [Level/rocksdb#24]
Doesn't rocksdb support linux kernal rather than darwin?
I tried to install it on node alpine version, but it shows like this:

```
../deps/leveldb/leveldb-rocksdb/util/io_posix.cc:16:22: fatal error: linux/fs.h: No such file or directory
 #include <linux/fs.h>
                      ^
compilation terminated.
make: *** [deps/leveldb/leveldb.target.mk:293: Release/obj.target/leveldb/deps/leveldb/leveldb-rocksdb/util/io_posix.o] Error 1
make: Leaving directory '/usr/src/app/node_modules/rocksdb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:135:13)
gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.9.49-moby
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/rocksdb
gyp ERR! node -v v9.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rocksdb@1.1.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rocksdb@1.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-19T12_01_47_614Z-debug.log
ERROR: Service 'node' failed to build: The command '/bin/sh -c npm rebuild' returned a non-zero code: 1
```

Thank you for give me a chance to submit an issue.

**Comment by plainweaver** [comment]
In current progress, it seemed package named `linux-headers` has to be installed additionally.
The error above has gone but I'm now facing new warnings.
Some modules print as next in compilation:

```
In file included from /root/.node-gyp/9.1.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/9.1.0/include/node/node.h:63,
                 from ../src/leveldown.cc:6:
/root/.node-gyp/9.1.0/include/node/v8.h:3115:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/root/.node-gyp/9.1.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/leveldown/src/leveldown_async.o
In file included from ../../nan/nan.h:192:0,
                 from ../src/leveldown.h:11,
                 from ../src/leveldown_async.cc:8:
../../nan/nan_maybe_43_inl.h: In function 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)':
../../nan/nan_maybe_43_inl.h:112:73: warning: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
                                                                         ^
In file included from /root/.node-gyp/9.1.0/include/node/v8.h:26:0,
                 from /root/.node-gyp/9.1.0/include/node/node.h:63,
                 from ../src/leveldown.h:8,
                 from ../src/leveldown_async.cc:8:
/root/.node-gyp/9.1.0/include/node/v8.h:3115:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/root/.node-gyp/9.1.0/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
```

I leave this issue to solve remaining warns despite it finishes building without an interception.

**Comment by vweevers** [comment]
I believe those deprecation warnings will go away once we update `nan` (#23) (nodejs/nan#708) and that they are safe to ignore.
